### PR TITLE
Update AkkaHttpConsulClient.scala

### PR DESCRIPTION
**Pull request by zocimek**
Fix deregister method according to consul docs 

https://www.consul.io/api/agent/service.html#deregister-service

### CODE REVIEW

**Comment by nonsleepr** [comment]
It looks like `DELETE` works just fine.

**EDIT:** It worked fine until we updated Consul.

**Comment by zocimek** [comment]
So can we merge the pull request ?

**Comment by dlouwers** [comment]
Merged. Bear with me for a new Maven release.

**Comment by nonsleepr** [comment]
Could that be published to Maven?

**Pull request merged**
